name: Upload to AnkiWeb
on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download release asset
        uses: robinraju/release-downloader@v1.11
        with:
          fileName: "CompreDef.ankiaddon"
          latest: true

      - name: Upload to AnkiWeb
        uses: danny900714/upload-anki-addon@v1.0.0
        with:
          username: ${{ secrets.ANKI_WEB_USERNAME }}
          password: ${{ secrets.ANKI_WEB_PASSWORD }}
          addon-id: "1619602654"
          title: "CompreDef"
          branches: 23.10.0-26.08+
          addon-files: CompreDef.ankiaddon
